#服务器端口号
server:
  port: 8888

#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.199.202.220:3306/yuezhan
    username: user9
    password: User123456

  #redis服务器
  redis:
    host: 127.0.0.1
    port: 6379

#\u914D\u7F6EFreeMarker\u6A21\u677F
    freemarker:
#\u6253\u5F00\u7F13\u5B58:true  \u5F00\u53D1\u9636\u6BB5\u5EFA\u8BAE\u5173\u95ED:false
        cache: false
        charset: utf-8
        content-type: text/html
        template-loader-path: classpath:/templates/
        suffix: .ftl
  #配置thymelelf模板参数
  thymeleaf:
    cache: false
    #应用于模板的模板模式
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

#
  #配置FreeMarker
#  freemarker:
#    #开发阶段建议false（开启缓存 false）
#    cache: false
#    charset: UTF-8
#    content-type: text/html
#    template-loader-path: classpath:/templates/
#    suffix: .ftl
#别名定义
mybatis:
  type-aliases-package: com.gaoshu.pojo
  #
  #mapper-locations:
  #config-locations: