server:
    port: 8888

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://121.199.202.220:3306/flower
        username: user12
        password: User123456

    freemarker:
        cache: false
        charset: utf-8
        content-type: textml
        template-loader-path: classpath:/templates/
        suffix: .ftl


mybatis:
    type-aliases-package: com.gaoshu.pojo

#mapper-locations: classpath: mapper/*Mapper.xml
#config-location: classpath: SqlMapConfig.xml
